# Generated by Django 3.2.6 on 2021-09-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_type_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'Пользователь'), ('teacher', 'Учитель'), ('training', 'Учебный центр')], default='user', max_length=20, verbose_name='type'),
        ),
    ]
