# Generated by Django 3.2.6 on 2021-09-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'books_subjects',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, verbose_name='Время создание')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='uploads/books/images/%Y/%m/%d', verbose_name='Картинка')),
                ('file', models.FileField(blank=True, upload_to='uploads/books/files/%Y/%m/%d', verbose_name='Файл')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('unpublished', 'Не опубликовано')], max_length=20, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обновление')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.subject')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'books_books',
            },
        ),
    ]
