# Generated by Django 3.2.6 on 2021-09-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210928_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.PositiveSmallIntegerField(blank=True, unique=True, verbose_name=''),
        ),
    ]
