# Generated by Django 3.2.6 on 2021-09-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_grade_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelTable(
            name='grade',
            table='books_grades',
        ),
    ]
