# Generated by Django 3.2.6 on 2021-09-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210928_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Время создание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время обновление'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.PositiveSmallIntegerField(blank=True, unique=True, verbose_name='Класс'),
        ),
    ]
