# Generated by Django 3.2.6 on 2021-09-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210928_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='name',
            new_name='number',
        ),
    ]
