# Generated by Django 3.2.6 on 2021-09-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210929_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Издание',
                'verbose_name_plural': 'Издании',
                'db_table': 'books_publishers',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Дата издание'),
        ),
    ]
