# Generated by Django 3.2.6 on 2021-09-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Дата издание'),
        ),
    ]
