# Generated by Django 3.2.6 on 2021-09-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.PositiveIntegerField(blank=True, choices=[('pdf', 'PDF'), ('djvu', 'DJVU')], null=True, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='quality',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Качество'),
        ),
    ]
