# Generated by Django 3.2.6 on 2021-09-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20210929_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('scan', 'Skaner'), ('ebook', 'eBook')], null=True, verbose_name='Качество'),
        ),
    ]
