# Generated by Django 3.2.6 on 2021-09-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('djvu', 'DJVU')], max_length=10, null=True, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quality',
            field=models.CharField(blank=True, choices=[('ebook', 'eBook'), ('scan', 'Skaner')], max_length=10, null=True, verbose_name='Качество'),
        ),
    ]
