# Generated by Django 3.2.6 on 2021-09-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20210929_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на файл'),
        ),
    ]
