# Generated by Django 3.2.6 on 2021-08-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Район')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Адрес')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.district', verbose_name='Район')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Цпециальность')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название учебного заведение')),
                ('post', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата устройсва')),
                ('end_date', models.DateField(blank=True, verbose_name='Дата увальнения')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('sur_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Запасной телефон')),
                ('post', models.CharField(blank=True, max_length=100, verbose_name='Дольжность')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Телеграм')),
                ('youtube', models.CharField(blank=True, max_length=100, verbose_name='Ютуб')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Почта')),
                ('photo', models.ImageField(blank=True, upload_to='uploads/photos/Y%/m%/d%/', verbose_name='Фото')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.location', verbose_name='Адрес')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.specialization', verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Названия')),
                ('image', models.ImageField(upload_to='uploads/portfolios/image/Y%/m%/d%/', verbose_name='Фото')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссыка')),
                ('file', models.FileField(blank=True, upload_to='uploads/portfolios/file/Y%/m%/d%/', verbose_name='Файл')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Учитель')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Текст комментарии')),
                ('reply', models.IntegerField(blank=True, null=True, verbose_name='Ответ на')),
                ('status', models.CharField(default='moderation', max_length=10, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновление')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Учитель')),
            ],
        ),
    ]
