# Generated by Django 3.2.6 on 2021-08-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('disable', 'Отключен')], default=1, max_length=10, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
