# Generated by Django 3.2.6 on 2021-09-08 14:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='О себе'),
        ),
    ]
