# Generated by Django 3.2.6 on 2021-09-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_comment_portfolio_teacher_workplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='telegram',
        ),
    ]
