# Generated by Django 3.2.6 on 2021-08-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20210831_1925'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='teachers_comments',
        ),
        migrations.AlterModelTable(
            name='district',
            table='teachers_districts',
        ),
        migrations.AlterModelTable(
            name='location',
            table='teachers_locations',
        ),
        migrations.AlterModelTable(
            name='portfolio',
            table='teachers_portfolios',
        ),
        migrations.AlterModelTable(
            name='region',
            table='teachers_regions',
        ),
        migrations.AlterModelTable(
            name='specialization',
            table='teachers_specializations',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers_teachers',
        ),
        migrations.AlterModelTable(
            name='workplace',
            table='teachers_workplace',
        ),
    ]
