# Generated by Django 3.2.6 on 2021-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20210914_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='sur_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
    ]
