# Generated by Django 3.2.6 on 2021-08-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20210831_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Учитель'),
            preserve_default=False,
        ),
    ]
