# Generated by Django 3.2.6 on 2021-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_remove_teacher_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_repetiteur',
            field=models.BooleanField(blank=True, default=False, verbose_name='Занимается репититерством'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='price_per_hour',
            field=models.CharField(blank=True, max_length=10, verbose_name='Стоимость часа репититерство'),
        ),
    ]
