# Generated by Django 3.2.6 on 2021-08-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_workplace_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/portfolios/file/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='uploads/portfolios/image/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
