# Generated by Django 3.2.6 on 2021-09-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20210924_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_repetiteur',
            new_name='is_coach',
        ),
    ]
