# Generated by Django 3.2.6 on 2021-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20210831_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
