# Generated by Django 3.2.6 on 2021-08-31 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20210831_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='vote_score',
        ),
    ]
