# Generated by Django 3.2.6 on 2021-09-02 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teachers.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увальнения'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='teachers.teacher', verbose_name='Учитель'),
        ),
    ]
