# Generated by Django 3.2.6 on 2021-09-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_auto_20210902_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.CharField(max_length=255, null=True, verbose_name='Слаг'),
        ),
    ]
