# Generated by Django 3.2.6 on 2021-09-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_teacher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('male', 'Мурской'), ('female', 'Женский')], max_length=6, null=True, verbose_name='Пол'),
        ),
    ]
