# Generated by Django 3.2.6 on 2021-09-04 11:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0012_auto_20210904_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Учитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='teachers.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='О себе'),
        ),
    ]
