# Generated by Django 3.2.6 on 2021-09-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заканчивается в'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начинается в'),
        ),
    ]
