# Generated by Django 3.2.6 on 2021-09-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210925_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('disable', 'Отключен')], default=1, max_length=10, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
