# Generated by Django 3.2.6 on 2021-09-24 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Слуг')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('about', models.TextField(blank=True, max_length=2000, verbose_name='О нас')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Учебный центр',
                'verbose_name_plural': 'Учебные центры',
                'db_table': 'trainings_trainings',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слуг')),
                ('price', models.CharField(blank=True, max_length=10, verbose_name='Цена')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Длительность')),
                ('duration', models.CharField(blank=True, max_length=10, verbose_name='Длительность')),
                ('about', models.TextField(blank=True, max_length=10000, verbose_name='О курсе')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='training.training', verbose_name='Учебный центр')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'trainings_courses',
            },
        ),
    ]
